### ISSUE TITLE
Rename Stash

### ISSUE THREAD

**Issue by migo315** [bestit/feature-toggle-bundle#19]
Rename `Stash` (eg. StashInterface) to `Repository` (eg. RepositoryInterface).

@Haehnchen 
Do you agree with this name or has another suggestion?

**Comment by Haehnchen** [comment]
Is more like a single Feature doc describes it as: `Check if the given feature name is active`.
So FeatureInterface, FeatureToggleInterface, FeatureActivationInterface, FeatureActivatorInterface, FeatureCollectorInterface, ...

Also think of BC. Just let your new interface extends StashInterface

**Comment by migo315** [comment]
Currently not needed
