### ISSUE TITLE
Add github repository label for searchability

### ISSUE THREAD

**Issue by Haehnchen** [bestit/feature-toggle-bundle#21]
Add github labels to this repository, eg add bundle, symfony, feature, ...

**Comment by migo315** [comment]
I added following:

- symfony
- feature
- feature-flags
- feature-toggles
- bundle
- rollout
- constraints

@Haehnchen More suggestions?

**Comment by Haehnchen** [comment]
good to me but  "toogle" in repo description ;)

**Comment by migo315** [comment]
I also added "toggle" ;-)
